### ISSUE TITLE
1. As a component, I want to be able to read from and write to the Firestore database

### ISSUE THREAD

**Issue by stacietaylorcima** [the-collab-lab/tcl-8-smart-shopping-list#1]
This is 1 of 2 stories that should be finished in the first week in order to enable further development.

AC:

* The following have been added as project dependencies: `firebase` & `react-firestore`
* Make a change in the Firestore database and it shows up in the app
* Make a change in the app and it shows up in the Firestore database

**Comment by stacietaylorcima** [comment]
- Google resources on deps
- Read docs on Firestore
- Look for example code (if necessary) 

What does this actually look like? Button?

**Comment by mxrcochxvez** [comment]
Found [this](https://medium.com/get-it-working/get-googles-firestore-working-with-react-c78f198d2364) handy medium article that will help with setting up firestore with my react app.

**Comment by mxrcochxvez** [comment]
Did not end up using this document, the [documentation](https://www.npmjs.com/package/react-firestore) helped tremendously with reading from the db
