### ISSUE TITLE
3. As a user, I want to set up a new shopping list so I can track purchased items

### ISSUE THREAD

**Issue by stacietaylorcima** [the-collab-lab/tcl-8-smart-shopping-list#3]
A shopping list consists of a set of items associated with a user’s token. Creating a new list consists of the following:

* Generate a new, unique token
* Save the token to `localStorage`
* Show the user the list view

The following script can be used to generate a suitable token: https://gist.github.com/segdeha/21a42618ce5a54916c5b58d36ec2992e

AC:

* For users who do not already have a token/list, a button or link exists at the `/` route (i.e. home screen) that allows them to create a new list
* Clicking the button/link generates a new token and saves it to `localStorage`
* Once the token has been created and saved, the user is redirected to the "list" view

**Comment by stacietaylorcima** [comment]
- Review how to store in localstorage
- No one needs to be logged in or anything. Anyone should be able to access app and generate a token by clicking a button. 
- Take a look at current structure of app and get more familiar.

**Comment by lilyhoratio** [comment]
From Andrew: 
"What you two can do for now is to use a dummy token. What I’d suggest is manually saving a token to localStorage and reading that out when you go to save the item to the database."

**Comment by AliLynne** [comment]
Steps I think we should take (please comment on or add anything I missed or am overthinking!) - 

- [ ] Create a new Welcome component

- [ ] Create function for generating token

- [ ] Create function for checking if token exists already

- [ ] Create function for saving to localStorage

- [ ] Create function for redirect to list?

- [ ] Make the button do all the things

**Comment by Lukabaramishvili** [comment]
> Steps I think we should take (please comment on or add anything I missed or am overthinking!) -
> 
> * [ ]  Create a new Welcome component
> * [ ]  Create function for generating token
> * [ ]  Create function for checking if token exists already
> * [ ]  Create function for saving to localStorage
> * [ ]  Create function for redirect to list?
> * [ ]  Make the button do all the things

This is perfect.
I think we can have 'history.push' using react-router to redirect to the list.
