### ISSUE TITLE
4. As a user, I want to add a new item to my shopping list

### ISSUE THREAD

**Issue by stacietaylorcima** [the-collab-lab/tcl-8-smart-shopping-list#4]
A shopping list item consists of the following data points:

* Name of item
* How soon are you likely to buy it again?
  * Soon (in the next 7 days)
  * Kind of soon (in the next 14 days)
  * Not soon (in the next 30 days)
* Last purchased date

AC:

* User is presented with a form that allows them to enter the name of the item and select how soon they anticipate needing to buy it again (Soon, Kind of soon, Not soon)
* When the user submits the form, the item is saved to the database, associated with the user’s token
* Along with the item name, an integer corresponding to the estimated number of days until next purchase is saved: 7 for “Soon”, 14 for “Kind of soon”, and 30 for “Not soon”
* The last purchased date should be set to `null` initially (i.e. you can create an item without purchasing it)

**Comment by lilyhoratio** [comment]
From Andrew: "What you two can do for now is to use a dummy token. What I’d suggest is manually saving a token to localStorage and reading that out when you go to save the item to the database."

**Comment by lilyhoratio** [comment]
@abidishajia made a few updates after our last push together! Still have some open bugs and questions:

- what is the best way to denote a default select option in React? https://stackoverflow.com/questions/21733847/react-jsx-selecting-selected-on-selected-select-option
- why is the console.log of enteredValue one step behind what is typed in input?
- should lastPurchaseDate be set to the current date when adding an item?
